### ISSUE TITLE
powershell脚本(1_Pcap2Session.ps1)内调用tool的路径与实际的0_Tool不符，且缺少finddupe程序文件

### ISSUE THREAD

**Issue by HFANFA** [cjx1016/Malicious-Traffic-Classification#3]
![image](https://user-images.githubusercontent.com/54758069/189605697-09caff4b-ed35-424c-9a34-b40c937fc674.png)
![image](https://user-images.githubusercontent.com/54758069/189605840-e0891b45-4571-4b12-83bb-bbf8b5229729.png)

**Comment by BeStrongok** [comment]
你好，这个是针对windows环境的可执行程序，建议在linux环境下执行sudo apt-get install fdupes命令。
