### ISSUE TITLE
OS問題

### ISSUE THREAD

**Issue by VickyChiu12** [cjx1016/Malicious-Traffic-Classification#5]
想請問這個程式是在Windows還是Linux上執行的?

**Comment by BeStrongok** [comment]
> 想請問這個程式是在Windows還是Linux上執行的?

你好，这个是在linux x86环境执行的

**Comment by VickyChiu12** [comment]
那如果我是linux x64會有影響嗎?

**Comment by BeStrongok** [comment]
> 那如果我是linux x64會有影響嗎?

没有影响的。
